server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeongsihoon/cloud-config
          repos:
            appname:
              uri: https://github.com/jeongsihoon/cloud-config
              cloneOnStart: true